# 全局配置
Global:
  env: dev
  gin_mode: debug # gin 框架允许环境 debug | release | test

# 服务配置
Server:
  ip: 127.0.0.1
  port: 8088
  read_timeout: 2000 # 读超时 ms
  write_timeout: 2000 # 写超时 ms

# 数据库配置
Database:
  mm_wiki:
    host: 127.0.0.1
    port: 3306
    name: mm_wiki2
    user: "root"
    pass: "123456"
    table_prefix: "mk_"
    conn_max_idle: 20
    conn_max_connection: 200
    conn_max_lifetime: 200 # 单位 s

# Upload 配置
Upload:
  doc_file: # 文档上传配置
    type: local # 上传方式 local | qiniu | aliyun
    local_dir: ./static/upload
    domain: http://localhost:8088

# 日志配置
Logger:
  default:
    - writer: console
      level: debug
    - writer: file
      level: info
      formatter: json
      writer_config:
        filename: ./logs/access.log
        max_age: 7
        max_backups: 10
        compress: false
        max_size: 10
    - writer: file
      level: error
      formatter: json
      writer_config:
        filename: ./logs/error.log
        max_age: 7
        max_backups: 10
        compress: false
        max_size: 10
